### ISSUE TITLE
Export selected

### ISSUE THREAD

**Issue by sirhaffy** [Tilapiatsu/blender-export_as_blend#2] opened 2024-03-19 09:46 UTC
When I select an object and export that as selected, the whole scene exports too. Blender 4.0.1 WIndows.
![Skärmavbild 2024-03-19 kl  10 44 37](https://github.com/Tilapiatsu/blender-export_as_blend/assets/10004320/8f0fb093-e54c-4bf0-aeb8-ed016b8391f9)

And thanks for this add on !!

**Comment by Tilapiatsu** [comment] 2024-03-19 20:42
Hey @sirhaffy !
Thanks for the feedback. I've just run other test on 4.01 and 4.1 release candidate without any issue. If `Selected Object` is 
set, I just get the selected object as expected.
I see that you have unticked `export to clean file`. have you tried with this enable ?
It ensure it will export to a file without any object. If unticked it will export to whatever startup file you have ( which may already contains objects, light, camera, default cube etc )

**Comment by sirhaffy** [comment] 2024-03-19 20:48
Yes I tried that also. When I do not tick the clean file it does not use my startup file. It uses a Blender default startup file.
Maby there is Somthing wrong with my Blender..

**Comment by Tilapiatsu** [comment] 2024-03-19 21:30
@sirhaffy when `Export to Clean File` unticked there was a bug which I've just fixed with V2.0.1 of this addon
Please give a try, and tell me if it works better.
But regarding the fact that the entire scene is exported instead of selected file, I really can't reproduce, so it is a bit hard for me to investigate your issue.
I guess it may be something related to your file or you setup. What you can do is to tick `Print Debug Message` in the export options.
Make the Export,
Then copy paste everything you have in the terminal to a text file and send it to me . You should many message starting by 'Import Command :'
I would also need to know the name of the object you tried to export.

**Comment by Tilapiatsu** [comment] 2024-11-13 07:46
@sirhaffy Did you had the chance to try with the new version ?

**Comment by Tilapiatsu** [comment] 2024-11-13 08:17
Someone else confirmed it worked fine with the fix. Closing the issue. feel free to open a new one if you still have issues with it :)

**Closed as completed by Tilapiatsu** 2024-11-13 08:17 UTC
